environment: development
log:
  level: debug
jwt:
  secret: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
security:
  memory: 1024
  iterations: 1
  parallelism: 1
  salt:
    length: 16
  key:
    length: 32
basic:
  auth:
    user: admin
    password: admin
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  database: example_db
redis:
  host: localhost:6379
  password:
namespace: project_template
upload:
  path: ./data
cdn:
  url: http://localhost:8000/v1/file
sentry:
  dsn: sentry_url
http:
  port: 8000
spec:
  path: ./docs/v1/swagger.json
  url: /v1/docs/swagger.json
  title: V1 documentation
  description: documentation
smtp:
  host: smtp.yandex.com
  port: 465
  username: "example@yandex.com"
  password: "password"